//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public int CounterID { get; set; }
        public int EmployeesCount { get; set; }
        public int OrdersCount { get; set; }
        public System.DateTime Date { get; set; }
    }
}
